apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Maven Java

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: https://github.com/cloudbees-io/checkout@v1
      - name: Build Java
        uses: docker://maven:3.9.9-eclipse-temurin-8-focal
        shell: sh
        run: |
          mvn clean install